### ISSUE TITLE
Same Command Printing 4 Times/File Management

### ISSUE THREAD

**Issue by SolarFlareHD** [hcgcloud/pterodactyl-unturned#3] opened 2020-03-08 23:25 UTC
The file management has been a mess since the new update, unturned -port for every individual server makes using my mod manager a literal nightmare since the directories vary. The location where everything is being stored and written is a problem. The console is printing out anything 4 times /saves/stops/teleports/commands/etc. Please look into this as your unturned egg is the best and we'd like to continue using it.

**Comment by tyson239** [comment] 2020-03-09 01:37
hello, could you provide some screenshots about the file management?

**Comment by SolarFlareHD** [comment] 2020-03-09 01:44
I'm unable to do that because we've fixed the file management issue within the egg itself but there are some other issues, do you possibly have a discord?

**Comment by tyson239** [comment] 2020-03-09 01:45
https://discord.gg/5KnNVfv

**Comment by tyson239** [comment] 2020-03-09 02:41
Reverted to previous version as the console won't work if start with `./Unturned_Headless.x86_64` directly. **Update the egg from the `master` branch and rebuild container will fix this issue.**

The issue of the name of the server folder is caused by a paste mistake, the reverted version don't have this issue, and has been fixed in the `develop` branch.

**Closed as completed by tyson239** 2020-03-09 02:41 UTC
